### DISCUSSION TITLE
How do I set username and password for Windows VMs?

### DISCUSSION THREAD

**Discussion by undeflnedCat** [eryph-org/eryph#336] [Q&A] [answered]
I might've just not understood it correctly, but it just doesn't accept `AdminUsername` and `AdminPassword`.

![Property AdminUsername is not allowed.yaml-schema: Fodder(513)](https://github.com/user-attachments/assets/601a3117-606b-4ba3-b29b-d4bc415adba7)

Also I _have_ a feeling that there are more issues than just it _🤔_

**Comment by fw2568** [comment, marked as answer]
Your welcome ;-) 
See this tutorial for a quick introduction to variables: https://github.com/eryph-org/samples/blob/main/tutorial/tutorial-3.yaml or even the full tutorial https://github.com/eryph-org/samples/blob/main/tutorial/README.md

For your Windows machine you can just rebind the fodder variables of the starter like this:

``` yaml
name: winsrv
parent: dbosoft/winsrv2022-standard/starter

variables:
  - name: Username
    required: true
  - name: Password
    required: true
    secret: true

fodder:
 - source: gene:dbosoft/starter-food:win-starter
   variables:
     - name: AdminUsername
       value: "{{ Username }}"
     - name: AdminPassword
       value: "{{ Password }}"
```

This is actually the best practice when using fodder with variables. However, for the starter tags, we made an exception to the rule because we want to avoid the user getting stuck on the first try just because the password is not accepted by Windows/Linux password rules.

To explain this a bit more, both catlets and fodder have a variables section. 
In the catlet section, you define which variables are available on the catlet (and all its children), and in the fodder section, you bind these variables to the variables in the fodder. 
See also the difference in names. Variables can also be used directly in the fodder using the same "{{ var }}" syntax, see the fodder definition for an example: https://genepool.eryph.io/b/dbosoft/starter-food/tags/1.3?gene=win-starter

And yes, we are still fixing some bugs in the App, so you are already a bit behind the current version (0.1.17). Any bug report or other question is welcome!
