### ISSUE TITLE
Add support for static IP address configuration on bridge adapters

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#144]
Network Provider configuration already contains a option to configure dhcp mode for bridge adapters. The adapter is auto enabled in this case.

``` yaml
network_providers:
- name: default
  type: overlay
  bridge_name: br-pif
  bridge_options: 
   host_ip_mode: dhcp
```

This should be extended by a option to set a ipv4 (and later ipv6 address via static configuration):

``` yaml
network_providers:
- name: default
  type: overlay
  bridge_name: br-pif
  bridge_options: 
   host_ip_mode: static
   host_ip_v4: 
      address: 
      gateway:
      dns_servers:
       - 8.8.8.8
       - 9.9.9.9
```

Static IP address configuration is already partially implemented for NAT adapters. What is missing is the configuration for gateway and DNS.
This configuration should only be applied when creating a bridge, not automatically as with NAT adapters. Therefore don't have to deal with the case where the configuration changes from dhcp to static or vice versa.
