### ISSUE TITLE
Environment don't use default settings

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#146]
Configure defaults and a environment without any datastores: 

``` yaml
defaults:
  vms: C:\vms\eryph
  volumes: C:\disks\eryph
datastores: 
environments: 
- name: staging
```

The VM is placed now on hyper-v default paths. E. g disks: 

C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\Eryph\

**Expected:**
The configured defaults should be used.
