### ISSUE TITLE
Catlet reverse config generation always contains drive size

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#177]
If a config is generated form a existing catlet it always contains the drive with drive size even if it the same size as in the parent: 

``` yaml
name: catlet
parent: dbosoft/winsrv2019-standard/20240125
drives:
- name: sda
  size: 40
```

Expected: 

``` yaml
name: catlet
parent: dbosoft/winsrv2019-standard/20240125
```

[AB#660](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/660)
