### ISSUE TITLE
catlet - maximum memory is not set

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#179]
config: 

``` yaml
memory: 
  startup: 2048
  minimum: 1024
  maximum: 8192
```

memory of created VM:

```
VMName DynamicMemoryEnabled Minimum(M) Startup(M) Maximum(M)
------ -------------------- ---------- ---------- ----------
node   True                 512        2048       1048576
```

[AB#662](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/662)
