### ISSUE TITLE
Creation of catlets: Converge command is not send

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#181]
In some cases - most probably missing or invalid configuration - the converge task is not executed but the create command succeeds:

e.g. 

``` yaml
name: cinc-server
parent: dbosoft/ubuntu-22.04/latest

project: cinc

memory: 
  startup: 4096

networks: 
- name: invalid
```

[AB#664](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/664)
