### ISSUE TITLE
Proposal: variables in fodder and catlet

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#186]
To make fodder genes more useful we should add a feature to use variables in fodder genes. 

Something like this: 

``` yaml
variables: 
  - name: a_variable
    required: true
    type: string | boolean | number
    secret: true    # prevents output in logs
    default: a_optional_default

fodder:
- name: admin-linux
  type: cloud-config
  secret: true
  content: |
    system_info:
      default_user:
        name: admin
    password: {{a_variable}}
```

Variables could then be set within a catlet e.g. 

``` yaml
variables: 
  - name: a_variable
    source: <food_reference>
    value: value
```

If a required variable is used without a default or a catlet configured value a error will thrown.

Same for logic should be possible for catlets and fodder genes. In case a source is present it, variable value will be required, in all other cases the entry is a variable declaration.

[AB#665](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/665)
