### ISSUE TITLE
Extend YAML parsing for cloud-config ( automatically map YAML to content)

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#187]
Currently it is required to pass cloud-init yaml as content as it should not be parsed:

``` yaml
- name: admin-windows
   type: cloud-config
   secure: true
   content: |
    users:
      - name: Admin
        groups: [ "Administrators" ]
```

We should extend the parsing logic to allow cloud-init sections to be handled automatically as content so user can declare it without the content marker  |

``` yaml
- name: admin-windows
   type: cloud-config
   secure: true
   content:
    users:
      - name: Admin
        groups: [ "Administrators" ]
```

[AB#666](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/666)
