### ISSUE TITLE
Variables are not set in fodder gene 

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#212]
Trying to set a samples using variables, but password cannot be set in referenced starter food.
Locks to be a bug or I missed something in configuration:

catlet: 

``` yaml
parent: dbosoft/ubuntu-22.04/starter

memory:
  startup: 1024

variables:
  - name: password
    required: true
    secret: true

fodder: 
 - source: gene:dbosoft/starter-food:linux-starter
   variables: 
   - name: password
     value: {{ password }}
```

Variable password is not set in starter food and keeps default value "admin".
Also tried source gene:dbosoft/starter-food/1.1:linux-starter without success.

For reference, the updated linux-starter 1.1 contains following variables: 

 
``` yaml
name: linux-starter

variables:
  - name: username
    value: admin
    required: true
  - name: password
    required: true
    secret: true
    value: admin
  - name: lockPassword
    type: boolean
    value: false    
  - name: sshPublicKey
    required: false

fodder:
- name: admin-linux
  type: cloud-config
  secret: true
  content: |
    users:
    - name: {{ username }}
      plain_text_passwd: {{ password }}
      group: admin
      lock_passwd: {{ lockPassword }}
      sudo: 'ALL=(ALL) NOPASSWD: ALL'
      ssh_authorized_keys:
      - {{ sshPublicKey }}

```

[AB#679](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/679)

**Comment by ChristopherMann** [comment]
The following catlet config works as expected:
```
parent: dbosoft/ubuntu-22.04/latest

memory:
  startup: 1024

variables:
  - name: password
    required: true
    secret: true

fodder: 
 - source: gene:dbosoft/starter-food:linux-starter
   variables: 
   - name: password
     value: "{{ password }}"
```

The part `value: "{{ password }}"` requires quotes. Otherwise, the YAML parser will attempt to parse this as a dictionary. See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#when-to-quote-variables-a-yaml-gotcha.

The second change (the parent is now `dbosoft/ubuntu-22.04/latest` instead of `dbosoft/ubuntu-22.04/starter`) is more interesting. Both the parent and the catlet specified the `linux-starter` food. After breeding and feeding, the `linux-starter` food of the parent was used which did not have the password variable bound.
