### ISSUE TITLE
Add option to apply fodder before parent fodder

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#230]
There should be a option to define that catlet fodder should be applied before the parent fodder and not after it as implemented currently. 

Use case: for secret fodder it is important that it is applied quickly because otherwise the secret will be reset if parent fodder takes a longer time. 

``` yaml
fodder:  
- name: admin-windows
  type: cloud-config
  secret: true
  order: appetizer 
  content: |
    users:
      - name: Admin
        groups: [ "Administrators" ]
        passwd: InitialPassw0rd 
```
