### ISSUE TITLE
Enable TPM capability

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#268]
Catlets can contain a capability tpm (all base catlets for windows already have this). 

TPM should be enabled if this capability is present or disabled if configured to disabled (same as for other capabilities).

sample catlet config:

``` yaml
capabilities:
- name: secure_boot
  details:
  - Template:MicrosoftWindows
- name: tpm
```

[AB#715](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/715)
