### ISSUE TITLE
Configure VLAN Id of catlets in flat networks

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#270]
VLANs are currently only configured for overlay networks, not for flat networks. 

With following flat network configuration:

``` yaml
- name: flat_eryph_vlan
  type: flat
  vlan: 100
  switch_name: Flat
```

the created catlet should have a network adapter with VLAN preconfigured to VLAN 100.
