### ISSUE TITLE
Static IP support for flat networks

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#276]
When flat networks are used, they currently rely on a DHCP server to be available on the flat network.
For OVS this is the same, but by design as the DHCP server on OVS is just a fake server to push DHCP options from OVN to the catlet.
For this scenario, the configuration of flat provider networks already allows to configure network / gateway and IP pools.

What is missing is that a catlet gets an IP address from the provider IP pool, which is then bound to a "flat network port" of the catlet. In addition, the configuration of cloud-init has to consider the static IP settings by resolving the provider network settings to a static IP configuration.

Example: 

``` yaml
provider_networks:
- name: flat
   type: flat
   network: 192.168.2.0/24
   gateway: 192.168.2.1
   subnets: 
   - name: default
     network: 192.168.2.0/24
     ip_pools: 
     - name: default
     - first_ip: 192.168.2.100
     - last_ip: 192.168.2.150
```

``` yaml
project_network:
- name: default
   provider: flat
   dhcp: false   # to be added 
```

This should then resolve to a catlet static IP address, like this:

ip: betwenn 192.168.2.100-192.168.2.150
network: /24
gateway: 192.168.2.1
