### ISSUE TITLE
Network adapters are not removed during catlet update

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#284]
When a catlet is updated, network adapters which have been removed from the catlet configuration are not removed from the VM.

## Steps
1. Create a new catlet with the following configuration:
   ```
   name: my-catlet
   parent: dbosoft/ubuntu-22.04/starter
   networks:
   - name: default
   ```
2. Update the catlet with the following configuration
   ```
   name: my-catlet
   parent: dbosoft/ubuntu-22.04/starter
   networks:
   - name: default
     mutation: remove
   ```

## Expected result
The network adapter is removed as the network has been removed. The VM has no network adapters configured.

## Actual result
The network adapter is still present in the VM.

[AB#726](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/726)
