### ISSUE TITLE
Dynamic Memory is always enabled even if not configured

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#289]
As specified in the [docs](https://www.eryph.io/docs/refs/specification-files) dynamic memory should only be enabled if capability is set or min / max memory is set. However a new catlet currently always enables dynamic memory by default. 

Example: 

`New-catlet -Parent dbosoft/winsrv2022-standard/starter`

`get-catlet -config`

=> dynamic memory is on:

``` yaml
version: 1.0
parent: dbosoft/winsrv2022-standard/starter-1.0
memory:
  minimum: 512
  maximum: 1048576
capabilities:
- name: dynamic_memory
```

[AB#728](https://dev.azure.com/dbosoft/eae53133-585f-4d55-8e1f-5cba6fd8ce3b/_workitems/edit/728)
