### ISSUE TITLE
Cannot add network adapter without network

### ISSUE THREAD

**Issue by ChristopherMann** [eryph-org/eryph#309]
It is not possible to add a network adapter to a catlet without also specifying a network. For example, the following config will not add the
adapter `test` to the catlet:
```
name: my-catlet
parent: dbosoft/ubuntu-22.04/starter
network_adapters:
- name: test
  mac_address: 02:04:06:08:10:12
```

The network adapter config is only used when an adapter with that name is used in a network configuration, e.g.:
```
name: my-catlet
parent: dbosoft/ubuntu-22.04/starter
network_adapters:
- name: test
  mac_address: 02:04:06:08:10:12
networks:
- name: default
  adapter_name: test
```
