### ISSUE TITLE
Resolved config validation don't detects unknown fodder name

### ISSUE THREAD

**Issue by fw2568** [eryph-org/eryph#315]
If fodder name is missing in source the catlet will be build sucessfully without the missing content. However this leads to a bad user experience in case fodder name is used in a wrong way. 

Tested with #313 

Example:

``` yaml
name: chocotest

parent: dbosoft/winsrv2022-standard/latest

fodder:
  - source: gene:dbosoft/chocolatey/0.5:manage
  - name: install
    source: gene:dbosoft/chocolatey/0.5:install
    variables:
      - name: app
        value: googlechrome
  - name: wrong_name
    source: gene:dbosoft/chocolatey/0.5:install
    variables:
      - name: app
        value: googlechrome
```

Name in second fodder is invalid (has to be "install" in the example), 

## Expected

A error is thrown in validation as referenced fodder cannot be found instead of silently dropping it.
